### ISSUE TITLE
Update to newest firebase versions

### ISSUE THREAD

**Issue by Butzlabben** [funwithflutter/lit_firebase_auth#14] opened 2020-08-30 12:13 UTC
Hi,

there some breaking changes in the newest versions of firestore and firebase_auth. I would like to use the new API and Crashlytics reports some crashes with the current firebase_auth version: https://github.com/FirebaseExtended/flutterfire/issues/2444

Sincerely,
Butzlabben

**Comment by funwithflutter** [comment] 2020-08-31 04:35
For now, this package is dependent on Firebase_auth_oauth to make the third party sign ins available (apple, etc). I'm waiting for that package to update before Lit can update.

Go give the issue an upvote! https://github.com/amrfarid140/firebase_auth_oauth/issues/17

If this is not resolved soon I will investigate implementing the third party oauth myself.

**Comment by CiriousJoker** [comment] 2020-09-01 03:50
Possible duplicate of #8

**Comment by funwithflutter** [comment] 2020-09-09 16:39
Yes, closing as this is a duplicate of #8.

**Closed by funwithflutter** 2020-09-09 16:39 UTC
